name: ecommerce_app
description: E-Commerce Flutter App with Cubit & Clean Architecture

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.4
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  dartz: ^0.10.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
